### ISSUE TITLE
Typo

### ISSUE THREAD

**Issue by mattp0123** [cryptolab-network/apps#213]
https://github.com/cryptolab-network/apps/blob/a923f9798d833138dcadfab65aae535e42a51092/src/AppLayout.tsx#L476

這網址有 typo：crytolab -> cryptolab
另外感覺改成超連結會比較好？

**Comment by jack77121** [comment]
[PR](https://github.com/cryptolab-network/apps/pull/215)

This will be fixed w/ next PR we create for main branch 😃
