### ISSUE TITLE
Some UI bugs

### ISSUE THREAD

**Issue by mattp0123** [cryptolab-network/apps#214]
https://github.com/cryptolab-network/apps/blob/a923f9798d833138dcadfab65aae535e42a51092/src/components/CardContent/index.tsx#L33-L36
https://github.com/cryptolab-network/apps/blob/a923f9798d833138dcadfab65aae535e42a51092/src/AppLayout.tsx#L796-L802
卡片跟連結加個 `cursor: pointer;`？

**Comment by jack77121** [comment]
[PR](https://github.com/cryptolab-network/apps/pull/216)

This will be fixed w/ next PR we create for main branch 😃
